name: "Feature request"
description: "Propose an enhancement"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please complete the details below.
  - type: input
    id: problem
    attributes:
      label: "Problem Statement"
      description: "What problem does this feature solve?"
      placeholder: "Describe the problem to solve"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "What do you want to happen?"
      placeholder: "Describe your proposed solution"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "What alternatives have you considered?"
      placeholder: "Describe alternative solutions or features"
    validations:
      required: false
  - type: textarea
    id: scope
    attributes:
      label: "Scope / Out of Scope"
      description: "Clarify what should and should not be included."
      placeholder: "In scope: ...\nOut of scope: ..."
    validations:
      required: false
  - type: textarea
    id: risks
    attributes:
      label: "Risks"
      description: "List potential risks or concerns."
      placeholder: "Technical, product, or timeline risks"
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Add any other context, references, or examples."
      placeholder: "Links, screenshots, prior art, etc."
    validations:
      required: false
